controllers:
  resource:
    path: ../src/Controller/
    namespace: App\Controller
  type: attribute
profile:
  path: /profile/{id}
  controller: App\Controller\ProfileController::showProfile

app_modify_profile:
  path: /modify-profile
  controller: App\Controller\MyProfileController::modifyProfile
  methods: [GET, POST]

app_notification_create:
  path: /notification/create
  controller: App\Controller\NotificationController::create
